version: "3"

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - hexlet-net

  app:
    image: yura2201/devops-for-programmers-project-74
    environment:
      DATABASE_HOST: ${vars.DATABASE_HOST}
      DATABASE_USERNAME: ${secrets.DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${secrets.DATABASE_PASSWORD}
      POSTGRES_DB: ${secrets.DATABASE_NAME}
    build:
      context: .
      dockerfile: Dockerfile.production

    command: npm test
    networks:
      - hexlet-net
    depends_on:
      - db
    restart: on-failure:5

networks:
  hexlet-net:
    driver: bridge

volumes:
  db:
    driver: local
