version: "3"

services:
  app:
    image: yura2201/devops-for-programmers-project-74
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.production

    command: npm test
    networks:
      - hexlet-net
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - hexlet-net

networks:
  hexlet-net:
    driver: bridge

volumes:
  db:
    driver: local
