version: "3"

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - hexlet-net

  app:
    image: yura2201/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
    command: npm test
    networks:
      - hexlet-net
    depends_on:
      - db
    restart: on-failure:5

networks:
  hexlet-net:
    driver: bridge

volumes:
  db:
    driver: local