version: "3"

services:
  app:
    image: yura2201/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production

    command: npm test
    networks:
      - hexlet-net
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - hexlet-net

networks:
  hexlet-net:
    driver: bridge

volumes:
  db:
    driver: local
