name: push

on:
  push:
    branches:
      - main

env:
  CI: true
  APP_IMAGE_NAME: yura2201/devops-for-programmers-project-74

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}
          cache-to: type=inline
          load: true
          tags: ${{ env.APP_IMAGE_NAME }}

      - name: Test
        run: |
          make ci

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest